# Generated by Django 5.2.10 on 2026-02-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_product_image_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
